[database]
path = "predictomatic.sqlite3"

[app]
admin_email = "admin@example.com"
email_suffix = "@example.com"
opening_balance_micros = 100_000_000

[server]
listen = "127.0.0.1:5639"
prefix = "/predict"

# For local development we can start additional servers where different users
# are logged in by default. These are only accepted when compiling for
# development, not when compiling in release mode.
# [[demo_server]]
# listen = "127.0.0.1:5640"
# prefix = ""
# unsafe_user_email  = "admin@example.com"

# [[demo_server]]
# listen = "127.0.0.1:5641"
# prefix = ""
# unsafe_user_email = "henk@example.com"

# [[demo_server]]
# listen = "127.0.0.1:5642"
# prefix = ""
# unsafe_user_email = "piet@example.com"

# The configuration file can contain markets to seed the database. These are
# primarily intended to make testing in local development easier.
[[market]]
slug = "predictomatic-demoable"
title = "Will the Predict-o-matic be demoable before the end of the hackathon?"
description = """
Resolves ‘Yes’ if the at the the hackathon presentations, the Predict-o-matic
is in a state where:
1) At least two users at the company are able to open it
2) They are able to make a prediction on at least one market.
"""
kind = "binary"
outcomes = ["Yes", "No"]
fund_micros = 150_000_000
