[server]
listen = "127.0.0.1:5639"
prefix = "/predict"

[database]
path = "predictomatic.sqlite3"

[app]
admin_email = "admin@example.com"
email_suffix = "@example.com"

[debug]
unsafe_default_email = "admin@example.com"
