// This file was generated by Squiller 0.5.0-dev (unspecified checkout).
// Input files:
// - database.sql

#![allow(unknown_lints)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::let_unit_value)]
#![allow(clippy::needless_lifetimes)]

use std::collections::hash_map::Entry::{Occupied, Vacant};
use std::collections::hash_map::HashMap;

use sqlite::{
    State::{Done, Row},
    Statement,
};

pub type Result<T> = sqlite::Result<T>;

pub struct Connection<'a> {
    connection: &'a sqlite::Connection,
    statements: HashMap<*const u8, Statement<'a>>,
}

pub struct Transaction<'tx, 'a> {
    connection: &'a sqlite::Connection,
    statements: &'tx mut HashMap<*const u8, Statement<'a>>,
}

pub struct Iter<'i, 'a, T> {
    statement: &'i mut Statement<'a>,
    decode_row: fn(&Statement<'a>) -> Result<T>,
}

impl<'a> Connection<'a> {
    pub fn new(connection: &'a sqlite::Connection) -> Self {
        Self {
            connection,
            // TODO: We could do with_capacity here, because we know the number
            // of queries.
            statements: HashMap::new(),
        }
    }

    /// Begin a new transaction by executing the `BEGIN` statement.
    pub fn begin<'tx>(&'tx mut self) -> Result<Transaction<'tx, 'a>> {
        self.connection.execute("BEGIN;")?;
        let result = Transaction {
            connection: self.connection,
            statements: &mut self.statements,
        };
        Ok(result)
    }
}

impl<'tx, 'a> Transaction<'tx, 'a> {
    /// Execute `COMMIT` statement.
    pub fn commit(self) -> Result<()> {
        self.connection.execute("COMMIT;")
    }

    /// Execute `ROLLBACK` statement.
    pub fn rollback(self) -> Result<()> {
        self.connection.execute("ROLLBACK;")
    }
}

impl<'i, 'a, T> Iterator for Iter<'i, 'a, T> {
    type Item = Result<T>;

    fn next(&mut self) -> Option<Result<T>> {
        match self.statement.next() {
            Ok(Row) => Some((self.decode_row)(self.statement)),
            Ok(Done) => None,
            Err(err) => Some(Err(err)),
        }
    }
}

pub fn ensure_schema_exists(tx: &mut Transaction) -> Result<()> {
    let sql = r#"
        create table if not exists accounts
        ( id       integer primary key
          -- 0 for the global accounts (points owned by the user or system), or the id
          -- of the market for accounts associated with a market.
        , market_id integer not null
          -- 0 for the native asset (points), or the id of an outcome for
          -- market accounts.
        , asset_id integer not null
          -- Email address for user-owned accounts, or "SYSTEM" for system-owned
          -- accounts.
        , owner    text not null
          -- Credits minus debits.
        , balance  integer not null
          -- The minimum allowed balance.
        , min_balance integer null
          -- The maximum allowed balance.
        , max_balance integer null
          -- Every user can have at most one account per asset per market.
        , unique (market_id, asset_id, owner)
          -- Balance constraints must be satisfied.
        , check (balance >= min_balance)
        , check (balance <= max_balance)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Events group one or more transfers. We could also call them "transaction",
        -- but that's confusing in a database.
        create table if not exists events
        ( id          integer primary key
        , created_at  text not null
        , created_by  text not null
        , description text not null
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table if not exists transfers
        ( id              integer primary key
        , event_id        integer not null references events (id)
        , from_account_id integer not null references accounts (id)
        , to_account_id   integer not null references accounts (id)
        , amount          integer not null
        , check (amount > 0)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table if not exists markets
        ( id          integer primary key
        , slug        text not null
        , created_at  text not null
        , kind        text not null
        , title       text not null
        , description text not null
        , unique (slug)
        , unique (title)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table if not exists outcomes
        ( id        integer primary key
        , market_id integer not null references markets (id)
        , value     text not null
        , unique (market_id, value)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Create the system points account. This balance can only go negative, as we
        -- mint points from here.
        insert into
          accounts
            (id, market_id, asset_id, owner, balance, min_balance, max_balance)
          values
            (0, 0, 0, 'SYSTEM', 0, null, 0)
          on conflict do nothing;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let result = match statement.next()? {
        Row => panic!("Query 'ensure_schema_exists' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

/// Return the account id a given (market_id, asset_id, owner).
pub fn get_account_id(
    tx: &mut Transaction,
    market_id: i64,
    asset_id: i64,
    owner: &str,
) -> Result<Option<i64>> {
    let sql = r#"
        select id from accounts
          where true
            and (market_id = :market_id)
            and (asset_id = :asset_id)
            and (owner = :owner);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, asset_id)?;
    statement.bind(3, owner)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => Some(decode_row(statement)?),
        Done => None,
    };
    if result.is_some() {
        if statement.next()? != Done {
            panic!("Query 'get_account_id' should return at most one row.");
        }
    }
    Ok(result)
}

/// Create a new account for a given (market_id, asset_id, owner), return its id.
pub fn create_account(
    tx: &mut Transaction,
    market_id: i64,
    asset_id: i64,
    owner: &str,
    min_balance: Option<i64>,
    max_balance: Option<i64>,
) -> Result<i64> {
    let sql = r#"
        insert into
          accounts
            (market_id, asset_id, owner, balance, min_balance, max_balance)
          values
            (:market_id, :asset_id, :owner, 0, :min_balance, :max_balance)
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, asset_id)?;
    statement.bind(3, owner)?;
    statement.bind(4, min_balance)?;
    statement.bind(5, max_balance)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_account' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_account' should return exactly one row.");
    }
    Ok(result)
}

/// Return the balance for the given account.
pub fn get_account_balance(tx: &mut Transaction, account_id: i64) -> Result<i64> {
    let sql = r#"
        select balance from accounts where id = :account_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, account_id)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'get_account_balance' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'get_account_balance' should return exactly one row.");
    }
    Ok(result)
}

/// Start a new event that can have transfers attached to it, returns its id.
pub fn create_event(tx: &mut Transaction, created_by: &str, description: &str) -> Result<i64> {
    let sql = r#"
        insert into
          events
          ( created_at
          , created_by
          , description
          )
          values
          ( strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
          , :created_by
          , :description
          )
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, created_by)?;
    statement.bind(2, description)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_event' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_event' should return exactly one row.");
    }
    Ok(result)
}

/// Record a transfer between two accounts.
pub fn create_transfer(
    tx: &mut Transaction,
    event_id: i64,
    from_account_id: i64,
    to_account_id: i64,
    amount: i64,
) -> Result<()> {
    let sql = r#"
        insert into transfers (event_id, from_account_id, to_account_id, amount)
          values (:event_id, :from_account_id, :to_account_id, :amount);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, event_id)?;
    statement.bind(2, from_account_id)?;
    statement.bind(3, to_account_id)?;
    statement.bind(4, amount)?;
    match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        update accounts
          set   balance = balance - :amount
          where (id = :from_account_id)
            and (:to_account_id is not null) and (:amount > 0);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, amount)?;
    statement.bind(2, from_account_id)?;
    statement.bind(3, to_account_id)?;
    match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        update accounts
          set   balance = balance + :amount
          where id = :to_account_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, amount)?;
    statement.bind(2, to_account_id)?;
    let result = match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

/// Return the slug of every market.
pub fn get_market_slugs<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
) -> Result<Iter<'i, 'a, String>> {
    let sql = r#"
        select slug from markets;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

#[derive(Debug)]
pub struct Market {
    pub id: i64,
    pub slug: String,
    pub kind: String,
    pub title: String,
    pub description: String,
}

pub fn get_market_by_slug(tx: &mut Transaction, slug: &str) -> Result<Option<Market>> {
    let sql = r#"
        select
            id
          , slug
          , kind
          , title
          , description
        from
          markets
        where
          slug = :slug;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, slug)?;
    let decode_row = |statement: &Statement| {
        Ok(Market {
            id: statement.read(0)?,
            slug: statement.read(1)?,
            kind: statement.read(2)?,
            title: statement.read(3)?,
            description: statement.read(4)?,
        })
    };
    let result = match statement.next()? {
        Row => Some(decode_row(statement)?),
        Done => None,
    };
    if result.is_some() {
        if statement.next()? != Done {
            panic!("Query 'get_market_by_slug' should return at most one row.");
        }
    }
    Ok(result)
}

/// Create a new market, return its id.
pub fn create_market(
    tx: &mut Transaction,
    slug: &str,
    kind: &str,
    title: &str,
    description: &str,
) -> Result<i64> {
    let sql = r#"
        insert into
          markets
          ( created_at
          , slug
          , kind
          , title
          , description
          )
          values
          ( strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
          , :slug
          , :kind
          , :title
          , :description
          )
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, slug)?;
    statement.bind(2, kind)?;
    statement.bind(3, title)?;
    statement.bind(4, description)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_market' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_market' should return exactly one row.");
    }
    Ok(result)
}

#[derive(Debug)]
pub struct Outcome {
    pub id: i64,
    pub value: String,
}

/// Return the possible outcomes of a given market.
pub fn get_outcomes<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, Outcome>> {
    let sql = r#"
        select id, value from outcomes
          where market_id = :market_id
          order by id asc;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(Outcome {
            id: statement.read(0)?,
            value: statement.read(1)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

/// Insert an outcome, return its id.
pub fn create_outcome(tx: &mut Transaction, market_id: i64, value: &str) -> Result<i64> {
    let sql = r#"
        insert into outcomes (market_id, value)
          values (:market_id, :value)
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, value)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_outcome' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_outcome' should return exactly one row.");
    }
    Ok(result)
}

#[derive(Debug)]
pub struct Account {
    pub id: i64,
    pub asset_id: i64,
    pub owner: String,
    pub balance: i64,
}

/// Return balances of all accounts related to the given market.
pub fn get_market_accounts<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, Account>> {
    let sql = r#"
        select
            id
          , asset_id
          , owner
          , balance
        from
          accounts
        where
          market_id = :market_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(Account {
            id: statement.read(0)?,
            asset_id: statement.read(1)?,
            owner: statement.read(2)?,
            balance: statement.read(3)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

// A useless main function, included only to make the example compile with
// Cargo’s default settings for examples.
#[allow(dead_code)]
fn main() {
    let raw_connection = sqlite::open(":memory:").unwrap();
    let mut connection = Connection::new(&raw_connection);

    let tx = connection.begin().unwrap();
    tx.rollback().unwrap();

    let tx = connection.begin().unwrap();
    tx.commit().unwrap();
}
