// This file was generated by Squiller 0.5.0-dev (unspecified checkout).
// Input files:
// - database.sql

#![allow(unknown_lints)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::let_unit_value)]
#![allow(clippy::needless_lifetimes)]

use std::collections::hash_map::Entry::{Occupied, Vacant};
use std::collections::hash_map::HashMap;

use sqlite::{
    State::{Done, Row},
    Statement,
};

pub type Result<T> = sqlite::Result<T>;

pub struct Connection<'a> {
    connection: &'a sqlite::Connection,
    statements: HashMap<*const u8, Statement<'a>>,
}

pub struct Transaction<'tx, 'a> {
    connection: &'a sqlite::Connection,
    statements: &'tx mut HashMap<*const u8, Statement<'a>>,
}

pub struct Iter<'i, 'a, T> {
    statement: &'i mut Statement<'a>,
    decode_row: fn(&Statement<'a>) -> Result<T>,
}

impl<'a> Connection<'a> {
    pub fn new(connection: &'a sqlite::Connection) -> Self {
        Self {
            connection,
            // TODO: We could do with_capacity here, because we know the number
            // of queries.
            statements: HashMap::new(),
        }
    }

    /// Begin a new transaction by executing the `BEGIN` statement.
    pub fn begin<'tx>(&'tx mut self) -> Result<Transaction<'tx, 'a>> {
        self.connection.execute("BEGIN;")?;
        let result = Transaction {
            connection: self.connection,
            statements: &mut self.statements,
        };
        Ok(result)
    }
}

impl<'tx, 'a> Transaction<'tx, 'a> {
    /// Execute `COMMIT` statement.
    pub fn commit(self) -> Result<()> {
        self.connection.execute("COMMIT;")
    }

    /// Execute `ROLLBACK` statement.
    pub fn rollback(self) -> Result<()> {
        self.connection.execute("ROLLBACK;")
    }
}

impl<'i, 'a, T> Iterator for Iter<'i, 'a, T> {
    type Item = Result<T>;

    fn next(&mut self) -> Option<Result<T>> {
        match self.statement.next() {
            Ok(Row) => Some((self.decode_row)(self.statement)),
            Ok(Done) => None,
            Err(err) => Some(Err(err)),
        }
    }
}

pub fn ensure_schema_versions_exists(tx: &mut Transaction) -> Result<()> {
    let sql = r#"
        create table if not exists schema_versions
          ( version    integer not null
          , created_at text not null
          );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let result = match statement.next()? {
        Row => panic!("Query 'ensure_schema_versions_exists' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

/// Create the schema.
///
/// We always have the latest version of the schema here: it's useful to have a
/// reference of what the tables and their columns are.
///
/// For migrations, we have separate queries below. We only do migrations up; to
/// go down, simply restore a back-up of your SQLite file before the migration.
pub fn create_schema(tx: &mut Transaction) -> Result<()> {
    let sql = r#"
        insert into
          schema_versions (version, created_at)
        values
          (3, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table accounts
        ( id       integer primary key
          -- 0 for the global accounts (points owned by the user or system), or the id
          -- of the market for accounts associated with a market.
        , market_id integer not null
          -- 0 for the native asset (points), or the id of an outcome for
          -- market accounts.
        , asset_id integer not null
          -- Email address for user-owned accounts, or "SYSTEM" for system-owned
          -- accounts.
        , owner    text not null
          -- Credits minus debits.
        , balance  integer not null
          -- The minimum allowed balance.
        , min_balance integer null
          -- The maximum allowed balance.
        , max_balance integer null
          -- Every user can have at most one account per asset per market.
        , unique (market_id, asset_id, owner)
          -- Balance constraints must be satisfied.
        , check (balance >= min_balance)
        , check (balance <= max_balance)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Events group one or more transfers. We could also call them "transaction",
        -- but that's confusing in a database.
        create table events
        ( id          integer primary key
        , created_at  text not null
        , created_by  text not null
        , description text not null
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table transfers
        ( id              integer primary key
        , event_id        integer not null references events (id)
        , from_account_id integer not null references accounts (id)
        , to_account_id   integer not null references accounts (id)
        , amount          integer not null
        , check (amount > 0)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Records the balance of an account after an event affected the account.
        -- Multiple transfers may be part of the same event, this table only records
        -- the final balance after all transfers that are part of the event.
        create table balances
        ( id            integer primary key
        , account_id    integer not null references accounts (id)
        , event_id      integer not null references events (id)
        , balance_after integer not null
        , unique (account_id, event_id)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table markets
        ( id          integer primary key
        , slug        text not null
        , created_at  text not null
        , kind        text not null
        , title       text not null
        , description text not null
        , unique (slug)
        , unique (title)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Open and close events for the market. Per market there may be at most one
        -- event in the future, e.g. its scheduled open or close.
        create table market_statuses
        ( id           integer primary key
        , market_id    integer not null references markets (id)
        , effective_at text not null
        , status       text not null check (status in ('Open', 'Closed'))
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create index ix_market_statuses_market_id_effective_at
          on market_statuses (market_id, effective_at);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table outcomes
        ( id          integer primary key
        , market_id   integer not null references markets (id)
        , value       text not null
          -- The event in which this outcome was picked as the resolution.
        , resolved_in integer null references events (id)
        , unique (market_id, value)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- For resolved markets, we track the realized profit per participant.
        -- Every profit links to a resolution event.
        create table realized_profits
        ( id               integer primary key
        , market_id        integer not null references markets (id)
        , event_id         integer not null references events (id)
        , owner            text    not null
        , amount_in        integer not null
        , amount_out       integer not null
        , unique (market_id, owner)
        , check (amount_in > 0)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- Create the system points account. This balance can only go negative, as we
        -- mint points from here.
        insert into
          accounts
            (id, market_id, asset_id, owner, balance, min_balance, max_balance)
          values
            (0, 0, 0, 'SYSTEM', 0, null, 0)
          on conflict do nothing;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let result = match statement.next()? {
        Row => panic!("Query 'create_schema' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

pub fn migrate_schema_from_1_to_2(tx: &mut Transaction) -> Result<()> {
    let sql = r#"
        insert into
          schema_versions (version, created_at)
        values
          (2, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_1_to_2' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table balances
        ( id            integer primary key
        , account_id    integer not null references accounts (id)
        , event_id      integer not null references events (id)
        , balance_after integer not null
        , unique (account_id, event_id)
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_1_to_2' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        insert into balances
          ( account_id
          , event_id
          , balance_after
          )
        select
          accounts.id as account_id,
          events.id as event_id,
          coalesce((
            select sum(amount) from transfers
            where (transfers.event_id <= events.id) and (accounts.id = transfers.to_account_id)
          ), 0) - coalesce((
            select sum(amount) from transfers
            where (transfers.event_id <= events.id) and (accounts.id = transfers.from_account_id)
          ), 0)
        from
          events,
          accounts
        where
          exists (
            select 1 from transfers where
              (events.id = transfers.event_id)
              and (
                  (accounts.id = transfers.from_account_id) or
                  (accounts.id = transfers.to_account_id)
              )
          )
        order by
          event_id asc,
          account_id asc;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let result = match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_1_to_2' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

pub fn migrate_schema_from_2_to_3(tx: &mut Transaction) -> Result<()> {
    let sql = r#"
        insert into
          schema_versions (version, created_at)
        values
          (3, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_2_to_3' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create table market_statuses
        ( id           integer primary key
        , market_id    integer not null references markets (id)
        , effective_at text not null
        , status       text not null check (status in ('Open', 'Closed'))
        );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_2_to_3' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        create index ix_market_statuses_market_id_effective_at
          on market_statuses (market_id, effective_at);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_2_to_3' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- We backfill the open times of the markets to their creation time, for past
        -- markets there was no concept of creating them before they are open.
        insert into
          market_statuses (market_id, effective_at, status)
        select
          id, created_at, 'Open'
        from
          markets;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_2_to_3' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        -- We also backfill the close events from the resolutions.
        insert into
          market_statuses (market_id, effective_at, status)
        select
          o.market_id, e.created_at, 'Closed'
        from
          outcomes o,
          events e
        where
          o.resolved_in = e.id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let result = match statement.next()? {
        Row => panic!("Query 'migrate_schema_from_2_to_3' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

pub fn get_schema_version(tx: &mut Transaction) -> Result<i64> {
    let sql = r#"
        select coalesce(max(version), 0) from schema_versions;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'get_schema_version' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'get_schema_version' should return exactly one row.");
    }
    Ok(result)
}

/// Return the account id a given (market_id, asset_id, owner).
pub fn get_account_id(
    tx: &mut Transaction,
    market_id: i64,
    asset_id: i64,
    owner: &str,
) -> Result<Option<i64>> {
    let sql = r#"
        select id from accounts
          where true
            and (market_id = :market_id)
            and (asset_id = :asset_id)
            and (owner = :owner);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, asset_id)?;
    statement.bind(3, owner)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => Some(decode_row(statement)?),
        Done => None,
    };
    if result.is_some() {
        if statement.next()? != Done {
            panic!("Query 'get_account_id' should return at most one row.");
        }
    }
    Ok(result)
}

/// Create a new account for a given (market_id, asset_id, owner), return its id.
pub fn create_account(
    tx: &mut Transaction,
    market_id: i64,
    asset_id: i64,
    owner: &str,
    min_balance: Option<i64>,
    max_balance: Option<i64>,
) -> Result<i64> {
    let sql = r#"
        insert into
          accounts
            (market_id, asset_id, owner, balance, min_balance, max_balance)
          values
            (:market_id, :asset_id, :owner, 0, :min_balance, :max_balance)
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, asset_id)?;
    statement.bind(3, owner)?;
    statement.bind(4, min_balance)?;
    statement.bind(5, max_balance)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_account' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_account' should return exactly one row.");
    }
    Ok(result)
}

/// Return the balance for the given account.
pub fn get_account_balance(tx: &mut Transaction, account_id: i64) -> Result<i64> {
    let sql = r#"
        select balance from accounts where id = :account_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, account_id)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'get_account_balance' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'get_account_balance' should return exactly one row.");
    }
    Ok(result)
}

/// Start a new event that can have transfers attached to it, returns its id.
pub fn create_event(tx: &mut Transaction, created_by: &str, description: &str) -> Result<i64> {
    let sql = r#"
        insert into
          events
          ( created_at
          , created_by
          , description
          )
          values
          ( strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
          , :created_by
          , :description
          )
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, created_by)?;
    statement.bind(2, description)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_event' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_event' should return exactly one row.");
    }
    Ok(result)
}

/// Record a transfer between two accounts.
pub fn create_transfer(
    tx: &mut Transaction,
    event_id: i64,
    from_account_id: i64,
    to_account_id: i64,
    amount: i64,
) -> Result<()> {
    let sql = r#"
        insert into transfers
          ( event_id
          , from_account_id
          , to_account_id
          , amount
          )
          values
          ( :event_id
          , :from_account_id
          , :to_account_id
          , :amount
          );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, event_id)?;
    statement.bind(2, from_account_id)?;
    statement.bind(3, to_account_id)?;
    statement.bind(4, amount)?;
    match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        update accounts
          set   balance = balance - :amount
          where id = :from_account_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, amount)?;
    statement.bind(2, from_account_id)?;
    match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        update accounts
          set   balance = balance + :amount
          where id = :to_account_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, amount)?;
    statement.bind(2, to_account_id)?;
    match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => {}
    }

    let sql = r#"
        insert into
          balances
          ( event_id
          , account_id
          , balance_after
          )
        values
          ( :event_id
          , :from_account_id
          , (select balance from accounts where id = :from_account_id)
          ),
          ( :event_id
          , :to_account_id
          , (select balance from accounts where id = :to_account_id)
          )
        on conflict
          -- Overwrite a previous balance for this event, if any.
          -- We care only about the final balance per event.
          do update set balance_after = excluded.balance_after;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, event_id)?;
    statement.bind(2, from_account_id)?;
    statement.bind(3, to_account_id)?;
    let result = match statement.next()? {
        Row => panic!("Query 'create_transfer' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

/// Return the slug of every market.
pub fn get_market_slugs<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
) -> Result<Iter<'i, 'a, String>> {
    let sql = r#"
        select slug from markets;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

#[derive(Debug)]
pub struct Market {
    pub id: i64,
    pub slug: String,
    pub kind: String,
    pub title: String,
    pub description: String,
    pub age_seconds: i64,
}

pub fn get_market_by_slug(tx: &mut Transaction, slug: &str) -> Result<Option<Market>> {
    let sql = r#"
        select
            id
          , slug
          , kind
          , title
          , description
          , unixepoch() - unixepoch(created_at) as age_seconds
        from
          markets
        where
          slug = :slug;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, slug)?;
    let decode_row = |statement: &Statement| {
        Ok(Market {
            id: statement.read(0)?,
            slug: statement.read(1)?,
            kind: statement.read(2)?,
            title: statement.read(3)?,
            description: statement.read(4)?,
            age_seconds: statement.read(5)?,
        })
    };
    let result = match statement.next()? {
        Row => Some(decode_row(statement)?),
        Done => None,
    };
    if result.is_some() {
        if statement.next()? != Done {
            panic!("Query 'get_market_by_slug' should return at most one row.");
        }
    }
    Ok(result)
}

#[derive(Debug)]
pub struct MarketStatus {
    pub effective_at: String,
    pub status: String,
    pub is_future: i64,
}

pub fn get_market_statuses<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, MarketStatus>> {
    let sql = r#"
        select
            effective_at
          , status
          , unixepoch(effective_at) > unixepoch() as is_future
        from
          market_statuses
        where
          market_id = :market_id
        order by
          effective_at desc
        limit
          -- There should be at most one future event, so if we select 2, we also get
          -- the current status.
          2;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(MarketStatus {
            effective_at: statement.read(0)?,
            status: statement.read(1)?,
            is_future: statement.read(2)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

/// Create a new market, return its id.
pub fn create_market(
    tx: &mut Transaction,
    slug: &str,
    kind: &str,
    title: &str,
    description: &str,
) -> Result<i64> {
    let sql = r#"
        insert into
          markets
          ( created_at
          , slug
          , kind
          , title
          , description
          )
          values
          ( strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
          , :slug
          , :kind
          , :title
          , :description
          )
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, slug)?;
    statement.bind(2, kind)?;
    statement.bind(3, title)?;
    statement.bind(4, description)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_market' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_market' should return exactly one row.");
    }
    Ok(result)
}

#[derive(Debug)]
pub struct Outcome {
    pub id: i64,
    pub value: String,
    pub resolved_in: Option<i64>,
}

/// Return the possible outcomes of a given market.
pub fn get_outcomes<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, Outcome>> {
    let sql = r#"
        select
            id
          , value
          , resolved_in
        from
          outcomes
        where
          market_id = :market_id
        order by
          id asc;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(Outcome {
            id: statement.read(0)?,
            value: statement.read(1)?,
            resolved_in: statement.read(2)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

/// Insert an outcome, return its id.
pub fn create_outcome(tx: &mut Transaction, market_id: i64, value: &str) -> Result<i64> {
    let sql = r#"
        insert into outcomes (market_id, value)
          values (:market_id, :value)
          returning id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, value)?;
    let decode_row = |statement: &Statement| Ok(statement.read(0)?);
    let result = match statement.next()? {
        Row => decode_row(statement)?,
        Done => panic!("Query 'create_outcome' should return exactly one row."),
    };
    if statement.next()? != Done {
        panic!("Query 'create_outcome' should return exactly one row.");
    }
    Ok(result)
}

#[derive(Debug)]
pub struct MarketAccount {
    pub asset_id: i64,
    pub owner: String,
    pub balance: i64,
}

/// Return balances of all accounts related to the given market.
pub fn get_market_accounts<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, MarketAccount>> {
    let sql = r#"
        select
            asset_id
          , owner
          , balance
        from
          accounts
        where
          market_id = :market_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(MarketAccount {
            asset_id: statement.read(0)?,
            owner: statement.read(1)?,
            balance: statement.read(2)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

#[derive(Debug)]
pub struct UserPointsAccount {
    pub id: i64,
}

/// Return ids of all global (not associated with a market) points accounts.
/// Excludes the system account.
pub fn get_user_points_accounts<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
) -> Result<Iter<'i, 'a, UserPointsAccount>> {
    let sql = r#"
        select
            id
        from
          accounts
        where
          -- Market id 0 means no market, asset id 0 is the points asset.
          (market_id = 0) and (asset_id = 0) and (owner <> 'SYSTEM');
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let decode_row = |statement: &Statement| {
        Ok(UserPointsAccount {
            id: statement.read(0)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

#[derive(Debug)]
pub struct PointsAccount {
    pub owner: String,
    pub balance: i64,
}

/// Return balances of all global (not associated with a market) points accounts.
pub fn get_points_accounts<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
) -> Result<Iter<'i, 'a, PointsAccount>> {
    let sql = r#"
        select
            owner
          , balance
        from
          accounts
        where
          -- Market id 0 means no market, asset id 0 is the points asset.
          (market_id = 0) and (asset_id = 0);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    let decode_row = |statement: &Statement| {
        Ok(PointsAccount {
            owner: statement.read(0)?,
            balance: statement.read(1)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

pub fn create_realized_profit(
    tx: &mut Transaction,
    market_id: i64,
    event_id: i64,
    owner: &str,
    amount_in: i64,
    amount_out: i64,
) -> Result<()> {
    let sql = r#"
        insert into realized_profits
          ( market_id
          , event_id
          , owner
          , amount_in
          , amount_out
          )
        values
          ( :market_id
          , :event_id
          , :owner
          , :amount_in
          , :amount_out
          );
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, event_id)?;
    statement.bind(3, owner)?;
    statement.bind(4, amount_in)?;
    statement.bind(5, amount_out)?;
    let result = match statement.next()? {
        Row => panic!("Query 'create_realized_profit' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

#[derive(Debug)]
pub struct RealizedProfit {
    pub owner: String,
    pub amount_in: i64,
    pub amount_out: i64,
}

pub fn get_realized_profits<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, RealizedProfit>> {
    let sql = r#"
        select
            owner
          , amount_in
          , amount_out
        from
          realized_profits
        where
          market_id = :market_id
        order by
          amount_in - amount_out;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(RealizedProfit {
            owner: statement.read(0)?,
            amount_in: statement.read(1)?,
            amount_out: statement.read(2)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

pub fn create_resolution(tx: &mut Transaction, outcome_id: i64, event_id: i64) -> Result<()> {
    let sql = r#"
        update outcomes set resolved_in = :event_id where id = :outcome_id;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, event_id)?;
    statement.bind(2, outcome_id)?;
    let result = match statement.next()? {
        Row => panic!("Query 'create_resolution' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

#[derive(Debug)]
pub struct TradeActivity {
    pub event_id: i64,
    pub created_at: String,
    pub user_email: String,
    pub market_id: i64,
    pub market_slug: String,
    pub market_title: String,
    pub outcome_label: String,
    pub asset_id: i64,
    pub amount_bought: i64,
}

/// Select all trades made up to and including the given event id,
/// or NULL to get the most recent trades.
pub fn get_trade_activity_until<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    limit: i64,
    event_id: Option<i64>,
) -> Result<Iter<'i, 'a, TradeActivity>> {
    let sql = r#"
        select
            e.id as event_id
          , e.created_at as created_at
          , a.owner as user_email
          , a.market_id as market_id
          , m.slug  as market_slug
          , m.title as market_title
          , o.value as outcome_label
          , a.asset_id as asset_id
          , t.amount as amount_bought
        from
          events e,
          transfers t,
          accounts a,
          markets m,
          outcomes o
        where
          ((:event_id is null) or (e.id <= :event_id))
          and (e.description = 'Trade')
          and (t.event_id = e.id)
          and (t.to_account_id = a.id)
          and (a.owner <> 'SYSTEM')
          and (a.market_id = m.id)
          and (a.asset_id = o.id)
        order by
          e.id desc
        limit
          :limit;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, event_id)?;
    statement.bind(2, limit)?;
    let decode_row = |statement: &Statement| {
        Ok(TradeActivity {
            event_id: statement.read(0)?,
            created_at: statement.read(1)?,
            user_email: statement.read(2)?,
            market_id: statement.read(3)?,
            market_slug: statement.read(4)?,
            market_title: statement.read(5)?,
            outcome_label: statement.read(6)?,
            asset_id: statement.read(7)?,
            amount_bought: statement.read(8)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

#[derive(Debug)]
pub struct MarketTradeActivity {
    pub event_id: i64,
    pub created_at: String,
    pub user_email: String,
    pub outcome_label: String,
    pub asset_id: i64,
    pub amount_bought: i64,
}

/// Select all trades made in this market (see also `get_trade_activity_until`).
pub fn get_trade_activity_by_market<'i, 't, 'a>(
    tx: &'i mut Transaction<'t, 'a>,
    market_id: i64,
) -> Result<Iter<'i, 'a, MarketTradeActivity>> {
    let sql = r#"
        select
            e.id as event_id
          , e.created_at as created_at
          , a.owner as user_email
          , o.value as outcome_label
          , a.asset_id as asset_id
          , t.amount as amount_bought
        from
          events e,
          transfers t,
          accounts a,
          outcomes o
        where
          (e.description = 'Trade')
          and (t.event_id = e.id)
          and (t.to_account_id = a.id)
          and (a.owner <> 'SYSTEM')
          and (a.market_id = :market_id)
          and (a.asset_id = o.id)
        order by
          e.id desc;
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    let decode_row = |statement: &Statement| {
        Ok(MarketTradeActivity {
            event_id: statement.read(0)?,
            created_at: statement.read(1)?,
            user_email: statement.read(2)?,
            outcome_label: statement.read(3)?,
            asset_id: statement.read(4)?,
            amount_bought: statement.read(5)?,
        })
    };
    let result = Iter {
        statement,
        decode_row,
    };
    Ok(result)
}

/// Insert a market status change effective at the given time.
/// Time must be ISO-8601 with Z offset.
pub fn set_market_status_at(
    tx: &mut Transaction,
    market_id: i64,
    effective_at: &str,
    status: &str,
) -> Result<()> {
    let sql = r#"
        insert into
          market_statuses (market_id, effective_at, status)
        values
          (:market_id, :effective_at, :status);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, effective_at)?;
    statement.bind(3, status)?;
    let result = match statement.next()? {
        Row => panic!("Query 'set_market_status_at' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

/// Insert a market status change effective now.
pub fn set_market_status_now(tx: &mut Transaction, market_id: i64, status: &str) -> Result<()> {
    let sql = r#"
        insert into
          market_statuses (market_id, effective_at, status)
        values
          (:market_id, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :status);
        "#;
    let statement = match tx.statements.entry(sql.as_ptr()) {
        Occupied(entry) => entry.into_mut(),
        Vacant(vacancy) => vacancy.insert(tx.connection.prepare(sql)?),
    };
    statement.reset()?;
    statement.bind(1, market_id)?;
    statement.bind(2, status)?;
    let result = match statement.next()? {
        Row => panic!("Query 'set_market_status_now' unexpectedly returned a row."),
        Done => (),
    };
    Ok(result)
}

// A useless main function, included only to make the example compile with
// Cargo’s default settings for examples.
#[allow(dead_code)]
fn main() {
    let raw_connection = sqlite::open(":memory:").unwrap();
    let mut connection = Connection::new(&raw_connection);

    let tx = connection.begin().unwrap();
    tx.rollback().unwrap();

    let tx = connection.begin().unwrap();
    tx.commit().unwrap();
}
